---
lang: pt-BR

title: "Carlinhos da Malvina: Algumas Histórias"

date: '`r format(Sys.time(), "%d de %B de %Y, %X")`'
summary_depth: 5
summary_float:
   collapsed: false
site: bookdown::bookdown_site

output: 
   bookdown::gitbook: default
documentclass: book
  
bibliography: [book.bib]

suppress-bibliography: false
link-citations: no
github-repo: Vermelho2/DonaMalvina
description: "JAZZ, BLUES, MPB, VIAGENS, COMIDINHAS, FILMES E OUTRAS DIVAGAÇÕES BY CARLINHOS DA MALVINA, UM BOM VIVANT NA SUA PRÓPRIA DEFINIÇÃO"
---

# __________________________________________ {-}
<center>
<span style="color:red">**Autor: Carlos Antunes de Souza**   

## _______________________________________________ {-}
<center>
<span style="color:blue">**JAZZ, BLUES, MPB, VIAGENS, COMIDINHAS, FILMES E OUTRAS DIVAGAÇÕES BY CARLINHOS DA MALVINA, UM BOM VIVANT NA SUA PRÓPRIA DEFINIÇÃO**
</center>

# Introdução
<div style="text-align: justify">
Muito bem: não tenho a menor pretensão de arrastar seguidores então vou escrevendo e mudando de assunto sem preocupação com a ordem cronológica ou um roteiro estudado ou pré estabelecido. A ideia é fazer apenas um registro de todas as experiências boas que vivi, assisti ou presenciei. Como já vivi bastante e pretendo viver muito mais, vou ter muita história para contar. Em matéria de viver eu quero dar VDO como se dizia no tempo do fusca que só marcava 120 km/h e depois embaixo estava escrito VDO que seria 140 ou 150 km/h.      
Veja que este não é um livro de História no sentido científico da palavra e, portanto, está sujeito as traições da minha memória. Sinta-se a vontade para nos comunicar algum deslize ou falha nas nossas recordações.     
Então, como dizia o bordão do contador de histórias do Castelo Rá-tim-bum, na TV Cultura, senta que lá vem história!       

